name: "Build & Test"

on:
  pull_request:
    paths-ignore:
      - "misc/**"
      - "web/**"
      - version
  push:
    paths-ignore:
      - "misc/**"
      - "web/**"
      - version

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v19
        with:
          extra_nix_config: |
            build-dir = ${{ runner.temp }}/nix-builds
      - run: findmnt -T "${RUNNER_TEMP}"
      - run: sudo chmod ugo+rwx "${RUNNER_TEMP}/nix-builds"
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: nix flake check
      - run: nix build .#static
